apiVersion: v1
kind: Service
metadata:
  name: elasticsearch2
  labels:
    app: elasticsearch2
spec:
  selector:
    app: elasticsearch2
  clusterIP: None
  ports:
    - port: 9200
      name: rest
    - port: 9300
      name: inter-node
